# -*- coding: utf-8 -*-
"""Tarot-digital.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n1ebD7gLtI5KRLtO9UCW9tboS7er8Ep-
"""

import random
import streamlit as st
from datetime import datetime
EXTRA_TIPS = [
    "Take a moment to reflect on this.",
    "Consider journaling your thoughts about this spread.",
    "How does this show up in your daily life?",
    "What lessons do you take away from this spread?",
    "What intention can you set based off this reading?",
    "Is there something you need to let go of?",
    "Reflect on how this energy affects your decisions.",
    "What lessons can you take from this?",
]

def extended_meaning(card):
    # Determine card type/category
    if card["name"] in [
        "The Fool", "The Magician", "The High Priestess", "The Empress",
        "The High Emperor", "The Hierophant", "The Lovers", "The Chariot",
        "Strength", "The Hermit", "The Wheel of Fortune", "Justice",
        "The Hanged Man", "Death", "Temperance", "The Devil", "The Tower",
        "The Star", "The Moon", "The Sun", "Judgement", "The World"
    ]:
        category_tip = "This card marks a significant life lesson or event."
    elif "Cups" in card["name"]:
        category_tip = "Focus on emotions and relationships."
    elif "Wands" in card["name"]:
        category_tip = "Look at your inspiration, energy, and actions."
    elif "Swords" in card["name"]:
        category_tip = "Pay attention to your thoughts, decisions, and challenges."
    elif "Pentacles" in card["name"]:
        category_tip = "Consider material, work, or practical matters."
    else:
        category_tip = "Reflect on this card’s message."

    random_tip = random.choice(EXTRA_TIPS)
    return f"{card['meaning']}. {category_tip} Advice: {random_tip}"
# -----------------------------
# FULL TAROT DECK
# -----------------------------
TAROT_CARDS = [
    {"name": "The Fool", "upright": "new beginnings, spontaneity, free spirit", "reversed": "recklessness, being taken advantage of, inconsideration"},
    {"name": "The Magician", "upright": "manifestation, resourcefulness, power", "reversed": "manipulation, poor planning, untapped talents"},
    {"name": "The High Priestess", "upright": "intuition, sacred knowledge, divine feminine", "reversed": "Secrets, disconnected from intuition, withdrawal"},
    {"name": "The Empress", "upright": "motherhood, fertility, nature", "reversed": "dependence, smothering, emptiness, nosiness"},
    {"name": "The High Emperor", "upright": "authority, structure, control, fatherhood", "reversed": "tyranny, rigidity, coldness"},
    {"name": "The Hierophant", "upright": "tradition, conformity, morality, ethics", "reversed": "rebellion, subversiveness, new approaches"},
    {"name": "The Lovers", "upright": "partnerships, duality, union", "reversed": "loss of balance, one-sidedness, disharmony"},
    {"name": "The Chariot", "upright": "direction, control, willpower", "reversed": "lack of control, lack of direction, aggresion"},
    {"name": "Strength", "upright": "inner strength, bavery, compassion, focus", "reversed": "self doubt, weakness, insecurity"},
    {"name": "The Hermit", "upright": "contemplation, search for truth, inner guidance", "reversed": "loneliness, isolation, lost your way"},
    {"name": "The Wheel of Fortune", "upright": "change, cycles, inevitable fate", "reversed": "no control, clinging to control, bad luck"},
    {"name": "Justice", "upright": "cause and effect, clarity, truth", "reversed": "dishonesty, unaccountability, unfairness"},
    {"name": "The Hanged Man", "upright": "sacrifice, release, martydom", "reversed": "stalling, needless sacrifice, fear of sacrifice"},
    {"name": "Death", "upright": "end of cycle, beginnings, change, metamorphosis", "reversed": "fear of change, holding on, stagnation, decay"},
    {"name": "Temperance", "upright": "middle path, patience, finding meaning", "reversed": "extremes, excess, lack of balance"},
    {"name": "The Devil", "upright": "addiction, materialism, playfulness", "reversed": "freedom, release, restoring control"},
    {"name": "The Tower", "upright": "sudden upheavel, broken pride, disaster", "reversed": "disaster avoided, delayed disaster, fear of suffering"},
    {"name": "The Star", "upright": "hope, faith, rejuvenantion", "reversed": "faithlessness, discouragement, insecurity"},
    {"name": "The Moon", "upright": "unconscious, illusions, intuition", "reversed": "confusion, fear, misinterpretation"},
    {"name": "The Sun", "upright": "joy, success, celebration, positivity", "reversed": "negativity, depression, sadness"},
    {"name": "Judgement", "upright": "reflection, reckoning, awakening", "reversed": "lack of self, awareness, dount, self loathing"},
    {"name": "The World", "upright": "fulfillment, harmony, completion", "reversed": "incompletion, no closure"},
    {"name": "Ace of Wands", "upright": "creation, willpower, inspiration, desire", "reversed": "lack of energy, lack of passion, boredom"},
    {"name": "Two of Wands", "upright": "planning, making decisions, leaving home", "reversed": "fear of change, playing safe, bad planning"},
    {"name": "Three of Wands", "upright": "looking ahead, expansion, rapid growth", "reversed": "obstacles, delays, frustration"},
    {"name": "Four of Wands", "upright": "community, home, celebration", "reversed": "lack of support, transience, home conflict"},
    {"name": "Five of Wands", "upright": "competition, rivalry, conflict", "reversed": "avoiding conflict, respecting differences"},
    {"name": "Six of Wands", "upright": "victory, success, public reward", "reversed": "excess pride, lack of recognition, punishment"},
    {"name": "Seven of Wands", "upright": "perseverance, defensive, maintaining control", "reversed": "give up, destroyed confidence, overwhelmed"},
    {"name": "Eight of Wands", "upright": "rapid action, movement, quick decisions", "reversed": "panic, waiting, slowdown"},
    {"name": "Nine of Wands", "upright": "resilience, grit, last stand", "reversed": "exhaustion, fatigue, questioning motivations"},
    {"name": "Ten of Wands", "upright": "accomplishment, responsibility, burden", "reversed": "inability to delegate, overstressed, burnt out"},
    {"name": "Page of Wands", "upright": "exploration, excitement, freedom", "reversed": "lack of direction, procrastination, creating conflict"},
    {"name": "Knight of Wands", "upright": "action, adventure, fearlessness", "reversed": "anger, impulsiveness, recklessness"},
    {"name": "Queen of Wands", "upright": "courage, determination, joy", "reversed": "selfishness, jealousy, insecurities"},
    {"name": "King of Wands", "upright": "big picture, leader, overcoming challenges", "reversed": "impulsive, overbearing, unachievable expectations"},
    {"name": "Ace of Cups", "upright": "Love, new relationships, compassion, creativity", "reversed": "Self-love, untuition, repressed emotions"},
    {"name": "Two of Cups", "upright": "Unified love, partnership, mutual attraction", "reversed": "Self-love, break-ups, disharmony, distrust"},
    {"name": "Three of Cups", "upright": "Celebration, friendship, creativity, collaborations.", "reversed": "Independence, alone time, hardcore partying, ‘three’s a crowd’."},
    {"name": "Four of Cups", "upright": "Meditation, contemplation, apathy, reevaluation", "reversed": "Retreat, withdrawal, checking in for alignment"},
    {"name": "Five of Cups", "upright": "Regret, failure, disappointment, pessimism", "reversed": "Personal setbacks, self-forgiveness, moving on"},
    {"name": "Six of Cups", "upright": "Revisiting the past, childhood memories, innocence, joy", "reversed": "Living in the past, forgiveness, lacking playfulness"},
    {"name": "Seven of Cups", "upright": "Opportunities, choices, wishful thinking, illusion", "reversed": "Alignment, personal values, overwhelmed by choices"},
    {"name": "Eight of Cups", "upright": "Disappointment, abandonment, withdrawal, escapism", "reversed": "Trying one more time, indecision, aimless drifting, walking away"},
    {"name": "Nine of Cups", "upright": "Contentment, satisfaction, gratitude, wish come true", "reversed": "Inner happiness, materialism, dissatisfaction, indulgence"},
    {"name": "Ten of Cups", "upright": "Divine love, blissful relationships, harmony, alignment", "reversed": "Disconnection, misaligned values, struggling relationships"},
    {"name": "Page of Cups", "upright": "Creative opportunities, intuitive messages, curiosity, possibility", "reversed": "New ideas, doubting intuition, creative blocks, emotional immaturity"},
    {"name": "Knight of Cups", "upright": "Creativity, romance, charm, imagination, beauty", "reversed": "Overactive imagination, unrealistic, jealous, moody"},
    {"name": "Queen of Cups", "upright": "Compassionate, caring, emotionally stable, intuitive, in flow", "reversed": "Inner feelings, self-care, self-love, co-dependency"},
    {"name": "King of Cups", "upright": "Emotionally balanced, compassionate, diplomatic", "reversed": "Self-compassion, inner feelings, moodiness, emotionally manipulative"},
    {"name": "Ace of Swords", "upright": "Breakthroughs, new ideas, mental clarity, success", "reversed": "Inner clarity, re-thinking an idea, clouded judgement"},
    {"name": "Two of Swords", "upright": "Difficult decisions, weighing up options, an impasse, avoidance", "reversed": "Indecision, confusion, information overload, stalemate"},
    {"name": "Three of Swords", "upright": "Heartbreak, emotional pain, sorrow, grief, hurt", "reversed": "Negative self-talk, releasing pain, optimism, forgiveness"},
    {"name": "Four of Swords", "upright": "Rest, relaxation, meditation, contemplation, recuperation", "reversed": "Exhaustion, burn-out, deep contemplation, stagnation"},
    {"name": "Five of Swords", "upright": "Conflict, disagreements, competition, defeat, winning at all costs", "reversed": "Reconciliation, making amends, past resentment"},
    {"name": "Six of Swords", "upright": "Transition, change, rite of passage, releasing baggage", "reversed": "Personal transition, resistance to change, unfinished business"},
    {"name": "Seven of Swords", "upright": "Betrayal, deception, getting away with something, acting strategically", "reversed": "Imposter syndrome, self-deceit, keeping secrets"},
    {"name": "Eight of Swords", "upright": "Negative thoughts, self-imposed restriction, imprisonment, victim mentality", "reversed": "Self-limiting beliefs, inner critic, releasing negative thoughts, open to new perspectives"},
    {"name": "Nine of Swords", "upright": "Anxiety, worry, fear, depression, nightmares", "reversed": "Inner turmoil, deep-seated fears, secrets, releasing worry"},
    {"name": "Ten of Swords", "upright": "Painful endings, deep wounds, betrayal, loss, crisis", "reversed": "Recovery, regeneration, resisting an inevitable end"},
    {"name": "Page of Swords", "upright": "New ideas, curiosity, thirst for knowledge, new ways of communicating", "reversed": "Self-expression, all talk and no action, haphazard action, haste"},
    {"name": "Knight of Swords", "upright": "Ambitious, action-oriented, driven to succeed, fast-thinking", "reversed": "Restless, unfocused, impulsive, burn-out"},
    {"name": "Queen of Swords", "upright": "Independent, unbiased judgement, clear boundaries, direct communication", "reversed": "Overly-emotional, easily influenced, bitchy, cold-hearted"},
    {"name": "King of Swords", "upright": "Mental clarity, intellectual power, authority, truth", "reversed": "Quiet power, inner truth, misuse of power, manipulation"},
    {"name": "Ace of Pentacles", "upright": "A new financial or career opportunity, manifestation, abundance", "reversed": "Lost opportunity, lack of planning and foresight"},
    {"name": "Two of Pentacles", "upright": "Multiple priorities, time management, prioritisation, adaptability", "reversed": "Over-committed, disorganisation, reprioritisation"},
    {"name": "Three of Pentacles", "upright": "Teamwork, collaboration, learning, implementation", "reversed": "Disharmony, misalignment, working alone"},
    {"name": "Four of Pentacles", "upright": "Saving money, security, conservatism, scarcity, control", "reversed": "Over-spending, greed, self-protection"},
    {"name": "Five of Pentacles", "upright": "Financial loss, poverty, lack mindset, isolation, worry", "reversed": "Recovery from financial loss, spiritual poverty"},
    {"name": "Six of Pentacles", "upright": "Giving, receiving, sharing wealth, generosity, charity", "reversed": "Self-care, unpaid debts, one-sided charity"},
    {"name": "Seven of Pentacles", "upright": "Long-term view, sustainable results, perseverance, investment", "reversed": "Lack of long-term vision, limited success or reward"},
    {"name": "Eight of Pentacles", "upright": "Apprenticeship, repetitive tasks, mastery, skill development", "reversed": "Self-development, perfectionism, misdirected activity"},
    {"name": "Night of Pentacles", "upright": "Abundance, luxury, self-sufficiency, financial independence", "reversed": "Self-worth, over-investment in work, hustling"},
    {"name": "Ten of Pentacles", "upright": "Wealth, financial security, family, long-term success, contribution", "reversed": "The dark side of wealth, financial failure or loss"},
    {"name": "Page of Pentacles", "upright": "Manifestation, financial opportunity, skill development", "reversed": "Lack of progress, procrastination, learn from failure"},
    {"name": "Knight of Pentacles", "upright": "Hard work, productivity, routine, conservatism", "reversed": "Self-discipline, boredom, feeling ‘stuck’, perfectionism"},
    {"name": "Queen of Pentacles", "upright": "Nurturing, practical, providing financially, a working parent", "reversed": "Financial independence, self-care, work-home conflict"},
    {"name": "King of Pentacles", "upright": "Wealth, business, leadership, security, discipline, abundance", "reversed": "Financially inept, obsessed with wealth and status, stubborn"}
]

# -----------------------------
# HELPER FUNCTIONS
# -----------------------------
def draw_card():
    card = random.choice(TAROT_CARDS)
    is_reversed = random.choice([True, False])
    return {
        "name": card["name"],
        "orientation": "Reversed" if is_reversed else "Upright",
        "meaning": card["reversed"] if is_reversed else card["upright"]
    }

def display_card(card):
    st.markdown(f"**{card['name']} ({card['orientation']})**")
    st.markdown(f"*Meaning:* {card['meaning']}")
    st.markdown("<br>",
    unsafe_allow_html=True)
    st.divider()

def show_extra_tip():
    tip = random.choice(EXTRA_TIPS)
    st.markdown(f"💫 **Extra Guidance** 💫 {tip}")

# -----------------------------
# SPREADS
# -----------------------------
def single_card_spread():
    st.subheader("🔮 Single Card Reading")
    card = draw_card()
    display_card(card)

def past_present_future_spread():
    st.subheader("🔮 Past, Present, Future Spread")
    positions = ["Past", "Present", "Future"]
    for pos in positions:
        st.markdown(f"**{pos}:**")
        card = draw_card()
        display_card(card)

def strength_weakness_spread():
    st.subheader("🔮 Strength and Weakness Spread")
    categories = ["Strength", "Weakness"]
    for label in categories:
        st.markdown(f"**{label}:**")
        card = draw_card()
        display_card(card)

def midwestern_gothic_spread():
    st.subheader("🔮 Midwestern Gothic Spread")
    categories = [
        "The Soul — your current situation, feelings, or head space",
        "The Water — your next step, the crucial thing to guide you forward",
        "The Haunted — what to watch out for",
        "The Famous — what to look forward to",
        "The Forgotten — what you must remember lest it be your downfall"
    ]
    for label in categories:
        st.markdown(f"**{label}:**")
        card = draw_card()
        display_card(card)

def mind_body_spirit_spread():
    st.subheader("🔮 Mind, Body, Spirit Spread")
    categories = ["Mind", "Body", "Spirit"]
    for label in categories:
        st.markdown(f"**{label}:**")
        card = draw_card()
        display_card(card)

def low_energy_spread():
    st.subheader("🔮 Low Energy Spread")
    categories = [
        "Why do I feel so tired?",
        "What is draining my energy?",
        "What can I do to make my energy flow again?"
    ]
    for label in categories:
        st.markdown(f"**{label}:**")
        card = draw_card()
        display_card(card)

# Update your print_card function:
def print_card(card):
    print(f"Card: {card['name']} ({card['orientation']})")
    print(f"Meaning: {extended_meaning(card)}")

# -----------------------------
# STREAMLIT APP
# -----------------------------
st.title("✨Welcome to the Tarot Reader✨")
st.markdown("✩₊˚.⋆☾⋆⁺₊✧ Let us see what the cards have in store for you ✩₊˚.⋆☾⋆⁺₊✧")
st.markdown(f"**Reading Time:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

spreads = {
    "Single Card": single_card_spread,
    "Past, Present, Future": past_present_future_spread,
    "Mind, Body, Spirit": mind_body_spirit_spread,
    "Strength and Weakness": strength_weakness_spread,
    "Midwestern Gothic": midwestern_gothic_spread,
    "Low Energy": low_energy_spread
}

choice = st.selectbox("Choose a spread:", list(spreads.keys()))

if st.button("Draw Cards"):
    spreads[choice]()
    show_extra_tip()
